# Generated by Django 5.2.8 on 2025-12-15 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrayedApp', '0002_customuser_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
